#+PROPERTY: header-args:emacs-lisp :tangle init.el :mkdirp yes
#+title: My Literate Emacs Configuration
#+author: Youssef K.

* Table of Contents                                                     :TOC:
- [[#basic-ui-tweaks][Basic UI tweaks]]
  - [[#minimal-ui][Minimal UI]]
  - [[#line-numbers][Line Numbers]]
  - [[#fonts][Fonts]]
  - [[#theme][Theme]]
  - [[#better-modline][Better Modline]]
  - [[#auto-highlight-symbol][Auto-highlight-symbol]]
  - [[#breadcrumbs][Breadcrumbs]]
- [[#package-management][Package Management]]
- [[#which-key][Which Key]]
- [[#evil-mode][Evil Mode]]
- [[#terminals][Terminals]]
  - [[#better-compilation-mode][Better Compilation Mode]]
- [[#markdown-mode][Markdown Mode]]
- [[#org-mode][Org Mode]]
  - [[#basic-configuration][Basic Configuration]]
  - [[#nicer-headings-bullets][Nicer Headings Bullets]]
  - [[#org-roam][Org-roam]]
  - [[#ox-epub][ox-epub]]
  - [[#toc-org][toc-org]]
  - [[#org-babel][Org Babel]]
- [[#enhanced-minibuffer][Enhanced Minibuffer]]
- [[#in-buffer-completion][In-buffer completion]]
- [[#dev][Dev]]
  - [[#tree-sitter-and-treesit-auto][Tree-sitter and treesit-auto]]
  - [[#rust][Rust]]
  - [[#nand2etris][nand2etris]]
  - [[#nix-mode][nix-mode]]
  - [[#language-servers][Language servers]]
  - [[#magit][Magit]]
- [[#file-management][File Management]]
  - [[#backup-files][Backup files]]
  - [[#dired][Dired]]
- [[#helpful--a-better-help][Helpful : A better help]]

* Basic UI tweaks

** Minimal UI

Makes Emacs look more minimal by removing the toolbar and other UI elements

#+begin_src emacs-lisp

  ;; Keep our init.el clean
  (setq custom-file (locate-user-emacs-file "custom.el"))
  (load custom-file :no-error-if-file-is-missing)

  ;; Make Emacs more minimal
  (setq inhibit-startup-message t)
  (menu-bar-mode -1)
  (tool-bar-mode -1)
  (scroll-bar-mode -1)

#+end_src

** Line Numbers

Tweaks to display relative line numbers. Use the =no-line-numbers-modes= to specify the modes where line numbers will be disabled.

#+begin_src emacs-lisp

  ;; line numbers
  (global-display-line-numbers-mode t)
  (setq display-line-numbers-type 'relative)

  ;; Disable line numbers for some modes
  (setq no-line-numbers-modes '(org-mode-hook
  			      term-mode-hook
  			      shell-mode-hook
  			      eshell-mode-hook
  			      lisp-interaction-mode-hook))

  (dolist (mode no-line-numbers-modes)
    (add-hook mode (lambda () (display-line-numbers-mode 0))))

#+end_src

** Fonts

I am using the /JetBrains Mono Nerd Font/.

#+begin_src emacs-lisp

  (add-to-list 'default-frame-alist '(font . "JetBrainsMono Nerd Font 13"))

#+end_src

** Theme

The ef-themes are a collection of light and dark themes for GNU Emacs whose goal is to provide colorful ("pretty") yet legible options for users who want something with a bit more flair than the modus-themes.

#+begin_src emacs-lisp

  (use-package ef-themes
    :ensure t
    :init
    ;; This makes the Modus commands listed below consider only the Ef
    ;; themes.  For an alternative that includes Modus and all
    ;; derivative themes (like Ef), enable the
    ;; `modus-themes-include-derivatives-mode' instead.  The manual of
    ;; the Ef themes has a section that explains all the possibilities:
    ;;
    ;; - Evaluate `(info "(ef-themes) Working with other Modus themes or taking over Modus")'
    ;; - Visit <https://protesilaos.com/emacs/ef-themes#h:6585235a-5219-4f78-9dd5-6a64d87d1b6e>
    (ef-themes-take-over-modus-themes-mode 1)
    :bind
    (("<f5>" . modus-themes-rotate)
     ("C-<f5>" . modus-themes-select)
     ("M-<f5>" . modus-themes-load-random))
    :config
    ;; All customisations here.
    (setq modus-themes-mixed-fonts t)
    (setq modus-themes-italic-constructs t)

    ;; Finally, load your theme of choice (or a random one with
    ;; `modus-themes-load-random', `modus-themes-load-random-dark',
    ;; `modus-themes-load-random-light').
    (modus-themes-load-theme 'ef-elea-dark))

#+end_src 

** Better Modline

#+begin_src emacs-lisp

  (use-package doom-modeline
    :ensure t
    :init (doom-modeline-mode 1))

#+end_src

** Auto-highlight-symbol

#+begin_src emacs-lisp

  (use-package auto-highlight-symbol
    :ensure t
    :config
    (set-face-attribute 'ahs-face-unfocused nil
                        :background (catppuccin-color 'red)
  		      :slant 'italic)
    (global-auto-highlight-symbol-mode t))

#+end_src

** Breadcrumbs

#+begin_src emacs-lisp

  (use-package breadcrumb
    :ensure t
    :config
    (breadcrumb-mode))

#+end_src


* Package Management

I am using *use-package* to automate the installation and configuration of packages.

#+begin_src emacs-lisp

  (require 'package)
  (setq package-archives (append '(("melpa" . "https://melpa.org/packages/")
  				 ("org" . "https://orgmode.org/elpa/"))
  			       package-archives))

#+end_src


* Which Key

Which-key is a UI panel that shows up when you start pressing any keybinding. This helps in learning and remembering
all the keybinding.

#+BEGIN_SRC emacs-lisp

  ;; Which-Key section
  (use-package which-key
    :config
    (setq which-key-idle-delay 1)
    (which-key-mode 1))

#+END_SRC

* Evil Mode

I use /evil-mode/ and evil-collection to get Vi-style keybinding. Note that the =evil-collection-mode-list= variable determines the modes where evil-collection is enabled.

#+begin_src emacs-lisp

  (use-package evil
    :ensure t
    :init
    (setq evil-want-keybinding nil)
    :config
    (evil-mode 1))

  (use-package evil-collection
    :after evil
    :ensure t
    :config
    (evil-collection-init))

#+end_src


* Terminals

Since I am using the =M-s= prefix for /consult/ related commands, I need to unbind them in terminals I am using.

#+begin_src emacs-lisp

  (use-package term
    :config
    (setq explicit-shell-file-name "zsh")
    (unbind-key "M-s" term-mode-map))

  (use-package vterm
    :ensure t
    :config
    (unbind-key "M-s" vterm-mode-map)
    (setq vterm-shell "zsh")
    (setq vterm-buffer-name-string "vterm %s"))

  (use-package xterm-color
    :ensure t)

  (use-package em-hist
    :ensure nil
    :bind (:map eshell-hist-mode-map
                ("M-s" . nil)))

  (use-package eshell
    :hook (eshell-before-prompt-hook . (lambda ()
  				       (setq xterm-color-preserve-properties t)))
    :bind (:map eshell-mode-map
                ("M-s" . nil)
                :map eshell-hist-mode-map
                ("M-s" . nil)))

#+end_src

** Better Compilation Mode

By default, the compilation mode doesn't show ANSI escape sequences properly. This will fix that.

#+begin_src emacs-lisp

  (use-package compile
    :ensure nil
    :config
    (setq compilation-scroll-output 1)
    :hook (compilation-filter . ansi-color-compilation-filter))

#+end_src

* Markdown Mode

#+begin_src emacs-lisp

  (use-package markdown-mode
    :ensure t)

#+end_src

* Org Mode

** Basic Configuration

#+begin_src emacs-lisp

  (use-package org
    :hook ((org-mode . org-indent-mode)
  	 (org-mode . visual-line-mode)
  	 (org-mode . flyspell-mode)))

#+end_src

** Nicer Headings Bullets

#+begin_src emacs-lisp

  (use-package org-bullets
    :ensure t
    :after org
    :hook (org-mode . org-bullets-mode))

#+end_src

** Org-roam

#+begin_src emacs-lisp

  (use-package org-roam
    :ensure t
    :custom
    (org-roam-directory (file-truename "~/org-roam"))
    :bind (("C-c n l" . org-roam-buffer-toggle)
           ("C-c n f" . org-roam-node-find)
           ("C-c n g" . org-roam-graph)
           ("C-c n i" . org-roam-node-insert)
           ("C-c n c" . org-roam-capture)
           ;; Dailies
           ("C-c n j" . org-roam-dailies-capture-today))
    :config
    ;; If you're using a vertical completion framework, you might want a more informative completion interface
    (setq org-roam-node-display-template (concat "${title:*} " (propertize "${tags:10}" 'face 'org-tag)))
    (org-roam-db-autosync-mode))

#+end_src

** ox-epub

Generate .epub files directly from OrgMode. This will export EPUB version 2, which should give broad compatibility. It should also be relatiely easy to convert the resulting .epub to a .mobi (Kindle).

Usage : Use =C-c C-e E e= to publish the current books as epub

#+begin_src emacs-lisp

  (use-package ox-epub
    :ensure t
    :after org)

#+end_src

** toc-org

=toc-org= helps you to have an up-to-date table of contents in org files without exporting, useful for easily jumping to headings and for using the org file in Github. The table of content will be added to the heading with the =:TOC:= tag. You can also use =TOC_2= to set the maximum depth to 2.

- Usage:
  * Use =C-c C-q= to add a =:TOC:= tag or =:TOC_num:= for maximum depth
  * Use =C-c C-o= (org-open-at-point) to jump to a link

#+begin_src emacs-lisp

  (use-package toc-org
    :ensure t
    :hook (org-mode . toc-org-mode)
    :after org)

#+end_src

** Org Babel

*** Auto-tangle

I define a =yos-org-babel-tangle= function and add it to the =after-save-hook=. The functions tangles the file if it is part of the =auto-tangle-files= list. I use the interactive =yos-auto-tangle-current-file= to add the currently visited file to the list. The list symbol is later added to the =savehist-additional-variables= for persistence between Emacs sessions.

#+begin_src emacs-lisp

  (defvar auto-tangle-files () "List of auto-tangled files.
  Used by yos-org-babel-tangle.
  Use the function yos-auto-tangle-current-file to add a file to the list.")

  (defun yos-org-babel-tangle ()
    "Auto-tangle a file if it's in the auto-tangle-files list"
    (if (member (buffer-file-name)
                (mapcar 'expand-file-name auto-tangle-files))
        ;; Dynamic scoping to the rescue
        (let ((org-confirm-babel-evaluate nil))
          (org-babel-tangle))))

  (add-hook 'after-save-hook #'yos-org-babel-tangle)

  (defun yos-auto-tangle-current-file ()
    "Add FILE to auto-tangle-files list.
          The function defaults to the currently visited file"
    (interactive)
    (let ((current-file (buffer-file-name)))
      (add-to-list 'auto-tangle-files current-file)
      (message "Auto-tangling %s" current-file)))

#+end_src

*** Babel Languages

To execute or export code in =org-mode= code blocks, we'll need to set up =org-babel-load-languages= for each language you'd like to use. [[https://orgmode.org/worg/org-contrib/babel/languages.html][This page]] documents all of the languages that you can use with =org-babel=.

Usage: Use =C-c C-c= to evaluate a source block.

*Note:* The package =rust-script= is required to run Rust code.

#+begin_src emacs-lisp

  					; Rust is not supported out of the box so we need this package.
  (use-package ob-rust
    :ensure t)

  (org-babel-do-load-languages
   'org-babel-load-languages
   '((python . t)
     (rust . t)
     (org . t)))

#+end_src

* Enhanced Minibuffer

I use /Vertico/, /Marginalia/, /Orderless/ and /Consult/ to enhance the minibuffer and the overall functionality.

#+begin_src emacs-lisp

  ;; Enable Vertico.
  (use-package vertico
    :ensure t
    :init
    (vertico-mode))

  (use-package marginalia
    :ensure t
    :init
    (marginalia-mode))

  (use-package savehist
    :ensure t
    :init
    (savehist-mode)
    :config
    (add-to-list 'savehist-additional-variables 'auto-tangle-files))

  (use-package orderless
    :ensure t
    :config
    (setq completion-styles '(orderless basic))
    (setq completion-category-overrides '((file (styles partial-completion))))
    (setq completion-category-defaults nil) ;; Disable defaults, use our settings
    (setq completion-pcm-leading-wildcard t)) ;; Emacs 31: partial-completion behaves like substring

  (use-package consult
    :ensure t
    :config (recentf-mode 1)
    :bind (;; A recursive grep
  	 ("M-s M-g" . consult-grep)
  	 ;; Search for files names recursively
  	 ("M-s M-f" . consult-find)
  	 ;; Search through the outline (headings) of the file
  	 ("M-s M-o" . consult-outline)
  	 ;; Search the current buffer
  	 ("M-s M-l" . consult-line)
  	 ;; Switch to another buffer, or bookmarked file, or recently
  	 ;; opened file.
  	 ("M-s M-b" . consult-buffer)
  	 ;; I menu
  	 ("M-s M-i" . consult-imenu)))

#+end_src

* In-buffer completion

I use /Corfu/ and /Cape/ for in-buffer completion.

#+begin_src emacs-lisp

  (use-package corfu
    :ensure t
    :hook (after-init . global-corfu-mode)
    :bind (:map corfu-map ("<tab>" . corfu-complete))
    :config
    (setq tab-always-indent 'complete)
    (setq corfu-preview-current nil)
    (setq corfu-auto t
  	corfu-auto-delay 0.1
  	corfu-quit-no-match 'separator))

  (use-package cape
    :ensure t
    :init
    (add-hook 'completion-at-point-functions #'cape-dabbrev)
    (add-hook 'completion-at-point-functions #'cape-file)
    (add-hook 'completion-at-point-functions #'cape-elisp-block))

  (use-package kind-icon
    :ensure t
    :after corfu
    :config
    (add-to-list 'corfu-margin-formatters #'kind-icon-margin-formatter))

#+end_src

* Dev

** Tree-sitter and treesit-auto

Emacs 29, while featuring treesit.el and a convenient treesit-install-language-grammar, will not feature an intelligent way to choose between a default mode, such as python-mode, and its tree-sitter enhanced version, python-ts-mode. treesit-auto attempts to remedy that by adjusting the major-mode-remap-alist and treesit-language-source-alist, It also can download the grammars automatically if the =treesit-auto-install= variable is set.

#+begin_src emacs-lisp

  (use-package treesit
    :ensure nil
    :config
    (setq treesit-font-lock-level 4))

  (use-package treesit-auto
    :ensure t
    :config
    (setq treesit-auto-install 'prompt)
    (treesit-auto-add-to-auto-mode-alist 'all)
    (delete 'rust treesit-auto-langs)
    (global-treesit-auto-mode))

#+end_src

** Rust

#+begin_src emacs-lisp

  (use-package rust-mode
    :ensure t)

  (use-package rust-ts-mode
    :ensure t)

  (use-package rust-playground
    :ensure t)

#+end_src

** nand2etris

#+begin_src emacs-lisp

  (use-package yasnippet
    :ensure t) ;; needed by nand2tetris

  (use-package nand2tetris
    :ensure t)

#+end_src

** nix-mode

#+begin_src emacs-lisp

  (use-package nix-mode
    :ensure t
    :mode ("\\.nix\\'" "\\.nix.in\\'"))
  (use-package nix-drv-mode
    :ensure nix-mode
    :mode "\\.drv\\'")
  (use-package nix-shell
    :ensure nix-mode
    :commands (nix-shell-unpack nix-shell-configure nix-shell-build))
  (use-package nix-repl
    :ensure nix-mode
    :commands (nix-repl))

#+end_src


** Language servers

#+begin_src emacs-lisp

  (use-package eglot
    :hook (prog-mode . eglot-ensure))

  (use-package consult-eglot
    :ensure t)

#+end_src

** Magit

Magit is an interface to the version control system Git, implemented as an Emacs package. Magit aspires to be a complete Git porcelain. it is complete enough to allow even experienced Git users to perform almost all of their daily version control tasks directly from within Emacs.

#+begin_src emacs-lisp

  (use-package magit
    :config
    (setq magit-display-buffer-function 'magit-display-buffer-fullframe-status-v1)
    (setq magit-bury-buffer-function 'magit-restore-window-configuration))

#+end_src


* File Management

** Backup files

By default Emacs creates backup files in the same project directory, which can be annoying. So we fix that here.

#+begin_src emacs-lisp

  (setq backup-directory-alist            '((".*" . "~/.emacs_saves")))

#+end_src

** Dired

#+begin_src emacs-lisp

  (use-package dired
    :ensure nil
    :hook (dired-mode . dired-hide-details-mode))

  (use-package all-the-icons-dired
    :ensure t
    :hook (dired-mode . all-the-icons-dired-mode))

#+end_src

* Helpful : A better help

[[https://github.com/Wilfred/helpful][Helpful]] adds a lot of very helpful (get it?) information to Emacs' =describe-= command buffers.  For example, if you use =describe-function=, you will not only get the documentation about the function, you will also see the source code of the function and where it gets used in other places in the Emacs configuration.  It is very useful for figuring out how things work in Emacs.

#+begin_src emacs-lisp

  (use-package helpful
    :ensure t
    :bind
    ([remap describe-function] . helpful-callable)
    ([remap describe-command] . helpful-command)
    ([remap describe-variable] . helpful-variable)
    ([remap describe-key] . helpful-key))

#+end_src
